import { useEffect, useState } from 'react'
import { motion, AnimatePresence } from 'motion/react'
import { Eye, Play } from 'lucide-react'

export function LandingHero({ onStart, onDemo, onHowItWorks }: { onStart: () => void; onDemo: () => void; onHowItWorks: () => void }) {
  const [promoIndex, setPromoIndex] = useState(0)
  useEffect(() => { const timer = window.setInterval(() => setPromoIndex((current) => current === 0 ? 1 : 0), 4500); return () => window.clearInterval(timer) }, [])
  return <section className="landing-hero"><div className="landing-hero-grid"><div className="landing-copy"><span className="eyebrow">THE PHYSICAL CARD COMPANION</span><h1><span className="landing-title-line">Press your luck.</span><br /><em className="landing-title-line">Race to 200.</em></h1><p>Bring the table to life. Track the cards you actually flip, settle the round together, and keep the whole game moving.</p><div className="landing-actions"><button className="landing-primary" onClick={onStart}><Play size={18} /> Start banker mode</button><button className="landing-demo" onClick={onDemo}><Eye size={17} /> Try the demo</button><button className="landing-secondary" onClick={onHowItWorks}>How it works</button></div><div className="landing-facts" aria-label="Game highlights"><span><b>01</b>Physical deck</span><span><b>02</b>One device</span><span><b>03</b>Fast rounds</span></div></div><div className="landing-art"><span className="landing-art-label">TABLE NIGHT<br /><b>IS ON</b></span><AnimatePresence mode="wait"><motion.div key={`promo-glow-${promoIndex}`} className="landing-promo-glow" initial={{ opacity: 0, scale: .72, x: '-50%', y: '-50%' }} animate={{ opacity: .9, scale: 1, x: '-50%', y: '-50%' }} exit={{ opacity: 0, scale: 1.2, x: '-50%', y: '-50%' }} transition={{ duration: .7 }} /></AnimatePresence><AnimatePresence mode="wait">{promoIndex === 0 ? <motion.img key="promo-card" className="landing-promo-card" src="/assets/promo-1.png" alt="Flip 7 card game" initial={{ opacity: 0, scale: .94, x: '-50%', y: '-50%', rotate: 1 }} animate={{ opacity: 1, scale: 1, x: '-50%', y: '-50%' , rotate: 5 }} exit={{ opacity: 0, scale: 1.04, x: '-50%', y: '-50%', rotate: 9 }} transition={{ duration: .7 }} /> : <motion.img key="promo-player" className="landing-promo-player" src="/assets/promo-2.png" alt="A player pressing their luck" initial={{ opacity: 0, scale: .94, x: '-50%', y: '-50%', rotate: -1 }} animate={{ opacity: 1, scale: 1, x: '-50%', y: '-50%', rotate: -5 }} exit={{ opacity: 0, scale: 1.04, x: '-50%', y: '-50%', rotate: -9 }} transition={{ duration: .7 }} />}</AnimatePresence></div></div></section>
}
